In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(3,)

In [6]:
len(arr)

3

In [10]:
arr.shape?

Type:        tuple
String form: (3,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [8]:
type(arr.shape)

tuple

In [11]:
arr.dtype

dtype('int64')

In [12]:
len(arr.shape)

1

In [14]:
np.prod(arr.shape)

3

In [15]:
np.prod?

Signature:
np.prod(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `

In [18]:
mat = np.array([[1, 2], [1, 0], [2, 1]]); mat

array([[1, 2],
       [1, 0],
       [2, 1]])

In [20]:
len(mat.shape), np.prod(mat.shape)

(2, 6)

In [21]:
np.sum(mat), np.sum(mat, axis=0), np.sum(mat, axis=1)

(7, array([4, 3]), array([3, 1, 3]))

In [24]:
def inflate(input_matrix):
    res = []
    for row in range(0, input_matrix.shape[0]):
        res_row = []
        for col in range(0, input_matrix.shape[1]):
            submatrix = input_matrix[row:row + 1, col:col + 1]
            transformed = np.zeros((3, 3)) if submatrix == 0 else np.ones((3, 3))
            res_row.append(transformed)
        res.append(np.concatenate(res_row, axis=1))
    return np.concatenate(res, axis=0)

In [25]:
inflate(mat)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [28]:
np.tri(4).T # transpose

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [32]:
np.flip(np.tri(4), axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [3]:
a_scalar = np.array(1)

In [4]:
a_scalar.ndim

0

In [9]:
len(a_scalar.shape)

0

In [6]:
arr = np.array([1, 2])

In [7]:
arr.ndim

1

In [10]:
len(arr.shape)

1