In [1]:
import numpy as np
from itertools import cycle, islice

In [2]:
mat = np.random.randint(0, 10, (10, 10))

In [3]:
mat.shape

(10, 10)

In [4]:
mat

array([[1, 0, 4, 4, 6, 3, 2, 2, 6, 5],
       [9, 1, 8, 0, 9, 1, 6, 7, 7, 8],
       [3, 8, 6, 9, 6, 0, 7, 2, 3, 8],
       [9, 4, 2, 7, 1, 8, 2, 5, 5, 8],
       [3, 1, 3, 7, 9, 6, 9, 0, 5, 4],
       [3, 9, 2, 3, 6, 2, 6, 5, 3, 3],
       [9, 3, 5, 7, 6, 9, 9, 9, 4, 0],
       [6, 4, 1, 0, 0, 7, 1, 6, 1, 2],
       [6, 8, 5, 8, 5, 9, 7, 4, 2, 9],
       [2, 5, 1, 1, 6, 4, 1, 6, 0, 0]])

In [5]:
rows = range(mat.shape[0])

In [6]:
list(rows)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
rows_top, rows_bottom = rows[:5], rows[5:]

In [8]:
rows_top

range(0, 5)

In [9]:
rows_bottom

range(5, 10)

In [10]:
list(reversed(rows_bottom))

[9, 8, 7, 6, 5]

In [11]:
list(zip(rows_top, reversed(rows_bottom)))

[(0, 9), (1, 8), (2, 7), (3, 6), (4, 5)]

In [12]:
def gen_rows(num_rows):
    num_bottom_rows = num_rows // 2
    rows_top = range(0, num_rows - num_bottom_rows)
    rows_bottom = range(num_rows - num_bottom_rows, num_rows)
    

In [13]:
def direction():
    yield from cycle([(+1, 0), (0, +1), (-1, 0), (0, -1)])

In [14]:
list(zip(direction(), range(10)))

[((1, 0), 0),
 ((0, 1), 1),
 ((-1, 0), 2),
 ((0, -1), 3),
 ((1, 0), 4),
 ((0, 1), 5),
 ((-1, 0), 6),
 ((0, -1), 7),
 ((1, 0), 8),
 ((0, 1), 9)]

In [15]:
def spiral_matrix(mat):
    if mat.shape[0] < 1: # no more rows (stopping condition)
        return
    yield from mat[0, :] # top row
    yield from mat[1:, -1] # right column
    yield from reversed(mat[-1, :-1]) # bottom row (reversed)
    yield from reversed(mat[1:-1, 0]) # left column (reversed)
    yield from spiral_matrix(mat[1:-1, 1:-1]) # recursive call

In [16]:
g = spiral_matrix(mat)

for i in range(10):
    print(list(islice(g, 10)))

[1, 0, 4, 4, 6, 3, 2, 2, 6, 5]
[8, 8, 8, 4, 3, 0, 2, 9, 0, 0]
[6, 1, 4, 6, 1, 1, 5, 2, 6, 6]
[9, 3, 3, 9, 3, 9, 1, 8, 0, 9]
[1, 6, 7, 7, 3, 5, 5, 3, 4, 1]
[2, 4, 7, 9, 5, 8, 5, 8, 4, 3]
[9, 1, 4, 8, 6, 9, 6, 0, 7, 2]
[5, 0, 5, 9, 6, 1, 7, 0, 0, 1]
[5, 2, 3, 2, 7, 1, 8, 2, 9, 6]
[9, 9, 6, 7, 3, 7, 9, 6, 2, 6]


In [17]:
mat

array([[1, 0, 4, 4, 6, 3, 2, 2, 6, 5],
       [9, 1, 8, 0, 9, 1, 6, 7, 7, 8],
       [3, 8, 6, 9, 6, 0, 7, 2, 3, 8],
       [9, 4, 2, 7, 1, 8, 2, 5, 5, 8],
       [3, 1, 3, 7, 9, 6, 9, 0, 5, 4],
       [3, 9, 2, 3, 6, 2, 6, 5, 3, 3],
       [9, 3, 5, 7, 6, 9, 9, 9, 4, 0],
       [6, 4, 1, 0, 0, 7, 1, 6, 1, 2],
       [6, 8, 5, 8, 5, 9, 7, 4, 2, 9],
       [2, 5, 1, 1, 6, 4, 1, 6, 0, 0]])

In [45]:
next(g)

StopIteration: 

In [18]:
import pprint

pprint.pprint(list(spiral_matrix(mat)), compact=True)

[1, 0, 4, 4, 6, 3, 2, 2, 6, 5, 8, 8, 8, 4, 3, 0, 2, 9, 0, 0, 6, 1, 4, 6, 1, 1,
 5, 2, 6, 6, 9, 3, 3, 9, 3, 9, 1, 8, 0, 9, 1, 6, 7, 7, 3, 5, 5, 3, 4, 1, 2, 4,
 7, 9, 5, 8, 5, 8, 4, 3, 9, 1, 4, 8, 6, 9, 6, 0, 7, 2, 5, 0, 5, 9, 6, 1, 7, 0,
 0, 1, 5, 2, 3, 2, 7, 1, 8, 2, 9, 6, 9, 9, 6, 7, 3, 7, 9, 6, 2, 6]


In [71]:
def spiral_matrix_set(mat):
    if mat.shape[0] < 1: # no more rows (stopping condition)
        return
        
    new_vals = []
    for _ in mat[0, :]: # top row
        new_vals.append((yield))
    mat[0, :] = new_vals
    
    new_vals = []
    for _ in mat[1:, -1]: # right column
        new_vals.append((yield))
    mat[1:, -1] = new_vals

    new_vals = []
    for _ in mat[-1, :-1]: # bottom row (reversed)
        new_vals.append((yield))
    mat[-1, :-1] = list(reversed(new_vals))

    new_vals = []
    for _ in mat[1:-1, 0]: # left column (reversed)
        new_vals.append((yield))
    mat[1:-1, 0] = list(reversed(new_vals))

    yield from spiral_matrix_set(mat[1:-1, 1:-1]) # recursive call

In [54]:
def test():
    lst = [1, 2, 3]
    new_vals = []
    for x in lst:
        got = (yield)
        new_vals.append(got)
    lst[:] = new_vals
    print(lst)

In [79]:
import itertools

In [84]:
def fill_spiral(mat):
    gen = spiral_matrix_set(mat)
    gen.send(None)
    try:
        for x in itertools.count():
            gen.send(x)
    except StopIteration:
        pass

In [85]:
fill_spiral(mat)

In [88]:
mat = np.zeros((8, 8))

In [89]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
fill_spiral(mat)

In [91]:
mat

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [27., 28., 29., 30., 31., 32., 33.,  8.],
       [26., 47., 48., 49., 50., 51., 34.,  9.],
       [25., 46., 59., 60., 61., 52., 35., 10.],
       [24., 45., 58., 63., 62., 53., 36., 11.],
       [23., 44., 57., 56., 55., 54., 37., 12.],
       [22., 43., 42., 41., 40., 39., 38., 13.],
       [21., 20., 19., 18., 17., 16., 15., 14.]])

In [102]:
np.index_exp[:]

(slice(None, None, None),)

In [263]:
def spiral_matrix_index_exp(mat, c):
    rows, cols = mat.shape
    
    if rows < 1: # no more rows (stopping condition)
        return

    mat[0, :] = list(itertools.islice(c, cols))
    mat[1:, -1] = list(itertools.islice(c, rows - 1))
    mat[-1, 0:-1] = list(reversed(list(itertools.islice(c, cols - 1))))
    mat[1:-1, 0] = list(reversed(list(itertools.islice(c, rows - 2))))

    spiral_matrix_index_exp(mat[1:-1, 1:-1], c) # recursive call

In [264]:
np.index_exp[:,0,-1]

(slice(None, None, None), 0, -1)

In [265]:
np.arange(0, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [266]:
def fill_spiral2(mat):
    c = itertools.count()
    for index_exp in spiral_matrix_index_exp(mat):
        print(index_exp)
        mat[index_exp] = list(itertools.islice(c, np.product(mat[index_exp].shape)))

In [267]:
mat = np.zeros((8, 8))

In [270]:
spiral_matrix_index_exp(mat, itertools.count(100))

In [271]:
mat

array([[100., 101., 102., 103., 104., 105., 106., 107.],
       [127., 128., 129., 130., 131., 132., 133., 108.],
       [126., 147., 148., 149., 150., 151., 134., 109.],
       [125., 146., 159., 160., 161., 152., 135., 110.],
       [124., 145., 158., 163., 162., 153., 136., 111.],
       [123., 144., 157., 156., 155., 154., 137., 112.],
       [122., 143., 142., 141., 140., 139., 138., 113.],
       [121., 120., 119., 118., 117., 116., 115., 114.]])

In [124]:
c = itertools.count()

In [126]:
list(itertools.islice(c, 5))

[0, 1, 2, 3, 4]

In [127]:
list(itertools.islice(c, 5))

[5, 6, 7, 8, 9]

In [128]:
list(itertools.islice(c, 5))

[10, 11, 12, 13, 14]

In [140]:
a_idx = np.index_exp[:, 0]

In [137]:
a_idx.count(mat)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [149]:
np.product(mat[a_idx].shape)

8